### ISSUE TITLE
Waterways demo causes additional forces on the simulated body

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/hydro#11]
Throw a duck from the sky.

```
E 0:00:25.075   Face3::split_by_plane: Condition "above_count >= 4 && below_count >= 4" is true. Returned: 0
  <C++ Source>  core\math\face3.cpp:83 @ Face3::split_by_plane()
```

EXPLOSION!

Use https://github.com/fire/WaterwaysDemo/tree/hydro

**Comment by jonri** [comment]
I've reproduced this.  For what it's worth, the Face3::split_by_plane warning is a red herring, the Godot source claims this error condition is hit due to a "bug in the algo", but it also happens when a face on your hull is totally coplanar with the water (which won't cause us a problem).

**Comment by jonri** [comment]
This is probably another manifestation of #3, although I'd have to do some additional testing to see if the duck had achieved terminal velocity.

**Comment by fire** [comment]
Duplicate of https://github.com/godot-extended-libraries/hydro/issues/3.
