### ISSUE TITLE
Update to Godot 4

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/hydro#12]
Tracking issue

**Comment by fire** [comment]
@jonri I brute forced godot 4 into Hydro.

**Comment by fire** [comment]
Todo restore:

- [x] void HydroRigidDynamicBody::draw_debug_face(const Face3 &face,
		const Transform3D &transform) {
- [x] void HydroRigidDynamicBody::draw_debug_mesh(const ClippableMesh &mesh,
		const Transform3D &transform) {

**Comment by jacobpennington821** [comment]
Have been playing around with godot 4, would love to have hydro working there, has anything been done in this area recently? Happy to help out if someone points me in the right direction!

**Comment by fire** [comment]
I am in too many things. Let me know what problems you have with https://github.com/godot-extended-libraries/hydro/tree/4.0. 

I and @jonri can review.

**Comment by jonri** [comment]
I've been a bit busy myself, but I've also been holding off until GDExtensions were more stable to evaluate whether we would be able to switch over to that.

**Comment by fire** [comment]
https://github.com/benbot/hydro/tree/4.0 @jonri has the latest work.

The cube falls to the ground and then goes up.

**Comment by fire** [comment]
The latest hydro has the changes. The ocean is disabled.
