### ISSUE TITLE
"Known Issues" wiki link doesn't lead to any macro

### ISSUE THREAD

**Issue by sandsalamand** [godot-extended-libraries/hydro#18]
https://github.com/godot-extended-libraries/hydro/wiki#known-issues

The linked .cpp file doesn't appear to have any macro. Has this been changed, and the docs are out of date?

**Comment by jonri** [comment]
Good catch! The macro is removed entirely in the master branch, and if you switch over to the v3.5.1 tag you'll find the macro with a version guard already in place. I'll update the docs accordingly.

**Comment by jonri** [comment]
I removed the section about the macro from the wiki since the both the Godot 3 and 4 versions should do the right thing, and wrote down some actual known issues instead.
